// <auto-generated />
using System;
using Homework12.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Homework12.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231022180917_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Homework12.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "is an American sports drama film starring Sylvester Stallone as boxer Rocky Balboa. Production was organized and overseen by producers Irwin Winkler, Robert Chartoff and their company Chartoff-Winkler Productions, and John Evildsen, who directed the film from Stallone's screenplay, was hired as director. Other actors involved in the movie include Talia Shire, Burt Young, Carl Weathers as Apollo Creed, Burgess Meredith and others.",
                            Director = "Sylvester Stallone",
                            MovieName = "Rokki First blood",
                            Style = "Fighting"
                        },
                        new
                        {
                            Id = 2,
                            Description = "is an American sports drama film starring Sylvester Stallone as boxer Rocky Balboa. Production was organized and overseen by producers Irwin Winkler, Robert Chartoff and their company Chartoff-Winkler Productions, and John Evildsen, who directed the film from Stallone's screenplay, was hired as director. Other actors involved in the movie include Talia Shire, Burt Young, Carl Weathers as Apollo Creed, Burgess Meredith and others.",
                            Director = "Sylvester Stallone",
                            MovieName = "Rokki 2",
                            Style = "Fighting"
                        });
                });

            modelBuilder.Entity("Homework12.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("Room")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2023, 10, 22, 21, 9, 17, 581, DateTimeKind.Local).AddTicks(8420),
                            MovieId = 1,
                            Price = 100m,
                            Room = 2
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2023, 10, 22, 21, 9, 17, 581, DateTimeKind.Local).AddTicks(8470),
                            MovieId = 2,
                            Price = 200m,
                            Room = 6
                        });
                });

            modelBuilder.Entity("Homework12.Models.Session", b =>
                {
                    b.HasOne("Homework12.Models.Movie", "Movie")
                        .WithMany("Sessions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Homework12.Models.Movie", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
